### ISSUE TITLE
[Feature Request] Better handle products that have multiple variants

### ISSUE THREAD

**Issue by vesper8** [drawrowfly/amazon-product-api#15]
If you take this product as an example https://www.amazon.co.uk/AmazonBasics-KB-10KG-cast-iron-kettlebell-10kg/dp/B076QJY2FN

You see that this is defaulting to the 10kg kettlebell since that's the product assigned to that asin, but looking at the json output from amazon-buddy it's impossible to tell that this is about the 10kg kettlebell.

It would be great if the 'related products' could also be scraped so there would be links to the other kettlebells linked on that page (different weights in this case, but this would be the same for products with size and color variants)

And also if somehow the currently selected item could be parsed.. in this case the 10kg is selected and this is marked in the form of `Style Name: 10kg` on that product page

**Comment by drawrowfly** [comment]
Will be added to the todo list
