### ISSUE TITLE
Get varinats option list !

### ISSUE THREAD

**Issue by clipvui2512** [drawrowfly/amazon-product-api#22]
Can I get varinats option : color,size,ect... ?

**Comment by drawrowfly** [comment]
You can do it with the current version, data will be in the variants array

**Comment by clipvui2512** [comment]
Sorry but ...current verison not show product options color,size, type...

**Comment by drawrowfly** [comment]
This data is only available in single product details method(asin) https://github.com/drawrowfly/amazon-product-api#asin-output

**Comment by clipvui2512** [comment]
I checked , and this don't support product variants data, only title and image in asin output,
Json need look like:
{
variants :[
{
title : product.title
options : {  blue , XXL , woman}
Images : array...
},
{
title : product.title
options : {  red , M , woman}
Images : array...
},
]
}
