### ISSUE TITLE
Periodic empty results

### ISSUE THREAD

**Issue by dgz9** [drawrowfly/amazon-product-api#24]
Hi, is there limits from Amazon or do they IP block after a certain amount of attempts? I seem to be getting empty results periodically that become more frequent over time. Here's an example of what I may receive back in the results:

```
{
  result: [
    {
      title: '',
      description: '',
      feature_bullets: [],
      variants: [],
      categories: [],
      asin: 'B08HJS2JLJ',
      url: 'https://www.amazon.com/dp/B08HJS2JLJ',
      reviews: [Object],
      item_available: true,
      price: [Object],
      bestsellers_rank: [],
      main_image: '',
      total_images: 0,
      images: [],
      total_videos: 0,
      videos: [],
      delivery_message: '',
      product_information: [Object],
      badges: [Object],
      sponsored_products: [],
      also_bought: [],
      other_sellers: []
    }
  ]
}
```

I do currently have a `for...of` loop running to scrape data using an array of products by asin. Don't know if this would cause issues or not.

**Comment by drawrowfly** [comment]
Proxies will solve your problem

**Comment by bluemix** [comment]
@drawrowfly I've used proxies and retrieving the same results.

**Comment by bluemix** [comment]
I am wondering why Postman is fetching info correctly, but, here it returns empty results.

**Comment by drawrowfly** [comment]
Set session from your browser

**Comment by bluemix** [comment]
I am not really sure what do you mean exactly.
I've opened my Amazon account in a private tab and used the new cookie info, 
but, unfortunately, still getting empty results.
