### ISSUE TITLE
Retrieving price 0 for asin product

### ISSUE THREAD

**Issue by bluemix** [drawrowfly/amazon-product-api#28]
Hello dear;
After fetching [this item](https://www.amazon.com/dp/B001JTADUI/ref=cm_sw_r_cp_apa_fabc_p11SFbMWKCR42?fbclid=IwAR21vqFkuH9XW6_kt8-mtsC5NPtayWVwx0-BvCjeal51b80yZ_m2_bPhjcs) details, I received price of $0, although, it has _$13.98_ in it.
Here is my code:
```js
const asinInfo = await amazonScraper.asin({
  asin: 'B001JTADUI',
  country: 'US',
  cookie: 'session-id=222-22222-22222; session-id-time=222221l; ubid-main=444-4444-4444444',
});
```

I also tried with `cookie: ''` and got the same results.
Thanks in advance.

**Comment by bluemix** [comment]
[Another item](https://www.amazon.com/Apple-iPhone-256GB-Midnight-Green/dp/B0815BRQX7/ref=mp_s_a_1_2?dchild=1&keywords=iphone%2011%20pro%20max%20256%20verizon&qid=1605790656&sprefix=iphone%2011pro%20max%20256&sr=8-2&fbclid=IwAR0Y680hKTfGh6RPYgWhKtzBtjTAWfK104mJ0GTq16Kp_XSPdqXZyEtcGv4) with price $0.

**Comment by drawrowfly** [comment]
Unfortunately i can't reproduce the issue that you are describing, with valid cookies i'm getting back the price without any issues

Thank You

**Comment by bluemix** [comment]
Sorry, I was not taking real cookie data values. I was using random ones.
Now, it works and the price is fetched.
Thanks.
