### ISSUE TITLE
amazon-buddy asin [asin]" is broken

### ISSUE THREAD

**Issue by quinnpertuit1** [drawrowfly/amazon-product-api#30]
## Steps to Reproduce the Problem

  amazon-buddy asin B07V5JTMV9

## Specifications

  - Version: amazon-buddy 2.2.12
  - Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
  - Darwin Kernel Version 18.7.0  

## Actual Behavior

[
   {
      "title":"",
      "description":"",
      "feature_bullets":[],
      "variants":[],
      "categories":[],
      "asin":"B07V5JTMV9",
      "url":"https://www.amazon.com/dp/B07V5JTMV9",
      "reviews":{
         "total_reviews":0,
         "rating":0,
         "answered_questions":0
      },
      "item_available":true,
      "price":{
         "symbol":"$",
         "currency":"USD",
         "current_price":0,
         "discounted":false,
         "before_price":0,
         "savings_amount":0,
         "savings_percent":0
      },
      "bestsellers_rank":[],
      "main_image":"",
      "total_images":0,
      "images":[],
      "total_videos":0,
      "videos":[],
      "delivery_message":"",
      "product_information":{
         "dimensions":"",
         "weight":"",
         "available_from":"",
         "available_from_utc":"",
         "available_for_months":0,
         "available_for_days":0,
         "manufacturer":"",
         "model_number":"",
         "department":"",
         "qty_per_order":"na",
         "brand":""
      },
      "badges":{
         "amazon_сhoice":false,
         "amazon_prime":false
      },
      "sponsored_products":[],
      "also_bought":[],
      "other_sellers":[]
   }
]

## Expected Behavior

Data for product returned.

**Comment by drawrowfly** [comment]
Can't reproduce

Everything is working fine from mine side

Possible and common reason is your IP, it is blacklisted by the Amazon

**Comment by quinnpertuit1** [comment]
Thank you. I'm on VPN, the reviews pull fine. Would this still explain the product details not pulling?
