### ISSUE TITLE
Own HTML and Proxy

### ISSUE THREAD

**Issue by N1NG4** [drawrowfly/amazon-product-api#43]
A parameter is required for using own proxy. 

Also I have a special way in which i can get html of the page easily. So there should be a parameter in the product function in which If html parameter is given then asin and country parameter should not be required.

**Comment by N1NG4** [comment]
@drawrowfly

**Comment by drawrowfly** [comment]
If you have this special way then pull requests are welcome! And I have no idea what are you asking for

**Comment by drawrowfly** [comment]
country param is required in some cases because html content can vary in some marketplaces

**Comment by N1NG4** [comment]
Special way is 
In my most of the cases I don't use simple requests for scraping. I use any Headless Browser with Slemenium or Puppeteer. So, I want to use it here also in which there should be a parameter which will ask you if you want to use a headless browser instead of simple request. Also I want a Proxy feature in which I can use my own proxies.

**Comment by drawrowfly** [comment]
You can use proxies already , I just didn't updated the docs, will do it later today maybe . Regarding headless browsers I'm against such things, as there will be to many dependencies  and etc

**Comment by N1NG4** [comment]
Ok Thanks for Proxies :)
In future if you think to add Headless Browser or Something like this I am very thankful to you.
