### ISSUE TITLE
Error: 503

### ISSUE THREAD

**Issue by santiesque** [drawrowfly/amazon-product-api#44]
Anyone experiencing a 503 error on latest version >= 2.2.29?

...'To discuss automated access to Amazon data please contact api-services-support@amazon.com.'

**Comment by drawrowfly** [comment]
I guess I need to create an issue template, where people would need to provide more details about the issue .

**Comment by drawrowfly** [comment]
And yes i do confirm that requests are getting blocked and only because of the one header param **DNT:1**

Update to version 2.2.30
