### ISSUE TITLE
price wrong, decimal point missing using --country DE

### ISSUE THREAD

**Issue by LarsOlt** [drawrowfly/amazon-product-api#58]
When searching for products with --country DE all price property values are wrong.

**Example:** 

"asin": "B0953X8PX5",
    "price": {
        "discounted": true,
        "current_price": 16298,
        "currency": "EUR",
        "before_price": 16998,
        "savings_amount": 700,
        "savings_percent": 4.12
    },

**The correct price should be:** 
162.98 (current_price)
169.98 (before_price)

**Comment by drawrowfly** [comment]
Can't confirm

Tested latest version and everything is fine
