### ISSUE TITLE
EBC content scrapping

### ISSUE THREAD

**Issue by nirweiner2** [drawrowfly/amazon-product-api#59]
Hi.
Is there any way to get the EBC content of a certain product?

**Comment by drawrowfly** [comment]
Hi,

What is that?

**Comment by nirweiner2** [comment]
Hi. That is the "Branded" description
Look at this for example: https://www.amazon.com/Libbey-Mixologist-9-Piece-Cocktail-Set/dp/B00865PFNI
If you check the description it will be different than the actual description shown on the website.
It is called A+ content.
It overrides the underlying description
More information can be found here: https://sellercentral.amazon.com/gp/help/help.html?itemID=202102950
