### ISSUE TITLE
Is it still working? 

### ISSUE THREAD

**Issue by jxdesign** [drawrowfly/amazon-product-api#61]
Not sure it's working currently? Been getting a lot of blanks when running various commands on it. 

![image](https://user-images.githubusercontent.com/22303396/130163780-00175132-b0af-441e-8c5b-8136bd99d4dd.png)

Also getting this and then it's just a spinning circle:

![image](https://user-images.githubusercontent.com/22303396/130163996-1573e09c-f2e3-4eac-ba15-ca83ed77e7a6.png)

**Comment by mwaqarsikandar** [comment]
Yes, Its working fine

**Comment by drawrowfly** [comment]
Yes
