### ISSUE TITLE
Price is always 0

### ISSUE THREAD

**Issue by Bariskau** [drawrowfly/amazon-product-api#65]
I added cookies. But the result has not changed, price information is not coming. Is there a different parameter I need to add?

```
class ProductService {
    async getProduct(asin) {
        await amazonScraper.asin({
            asin: asin,
            country: 'US',
            cookie: "session-id=147-3348510-9162916; session-id-time=2082787201l; ubid-main=130-4538308-0250231;"
        }).then((res) => {
            res.result.map(item => {
                Product.updateOrCreate(item)
            })
        });
    };
}
```

**Comment by sohum124** [comment]
The same thing is happening to me. Its not for all products though

**Comment by Bariskau** [comment]
@sohum124 use my forked version

**Comment by Bariskau** [comment]
There are frequent changes in html tags on amazon.  Which means the scraper won't always work.  Must be constantly updated.  Unfortunately, this package is not constantly updated.  After forking, you need to make your own customizations.

**Comment by sohum124** [comment]
Yeah I also assumed the same thing as when I tried building my own with a recent video, the tag was different

**Comment by Bariskau** [comment]
@sohum124 In some marketplace the price came with the following css class, '.apexPriceToPay'. But most marketplace have been updated now you need to add this class '.priceToPay' as well.
