### ISSUE TITLE
Not able to load module 'amazon-buddy' in my js code

### ISSUE THREAD

**Issue by Akshitjariwala** [drawrowfly/amazon-product-api#66]
I am not able to load the 'amazon-buddy' module in my code and it is always giving 'Could not find module 'amazon-buddy''.
Even though i ran the npm command mentioned on the site to load the package. 
Could you please help ?

**Comment by drawrowfly** [comment]
Not package related problem

**Comment by Akshitjariwala** [comment]
The above issue is resolved. But now while i am trying to fetch any products using keyword it is showing Amazon Scraper StartedError: No more products error. Could you please help ?

**Comment by cvanvlack** [comment]
@Akshitjariwala, Did you ever solve this? I was searching how to get this running and I thought I would put what I had here.

I'm using firebase functions. In the `functions` directory, I ran
```
npm i amazon-buddy
```
My code is
```
import * as functions from "firebase-functions";
import * as amazonbuddy from "amazon-buddy";

export const searchForProducts =
  functions.https.onCall(async (data, context) => {

    const options = {
      keyword: "vacuum cleaner",
    };

    const output = await amazonbuddy.products(options);
    console.log(output);
    return output;
  });
```

**Comment by Akshitjariwala** [comment]
Try deleting the node_modules folder and do the 'npm install' once again to install and load all the dependencies from scratch. That worked for me.
