### ISSUE TITLE
Returned price, wrong decimal format.

### ISSUE THREAD

**Issue by blogolino** [drawrowfly/amazon-product-api#70]
Steps to reproduce, search for:
https://www.amazon.de/Schachspiel-Fantastische-Brettspiel-Reisespiele-Compilation/dp/B07H4KJ97V/

Sometimes you get:
```
current_price: 50
```
and sometimes:
```
current_price: 5000
```
and sometimes:
```
current_price: 50.00
```

**Comment by drawrowfly** [comment]
was fixed already
