### ISSUE TITLE
asin() does not return images data

### ISSUE THREAD

**Issue by TeddyPerkins** [drawrowfly/amazon-product-api#72]
For eg `amazon-buddy asin B01GW3H3U8` returns data with images value as empty array..

**Comment by xakep-sava** [comment]
@TeddyPerkins hi, I fixed the error and sent a [pull request](https://github.com/drawrowfly/amazon-product-api/pull/73/commits/ff6cb9b9502c5425ae2276b6a65c25f43b05ca92)

**Comment by drawrowfly** [comment]
merged
